Player:
  StartingHealth: 20
  MaxLives: 3
  MaxBullets: 100
  StartingBullets: 8
Ametralladora:
  Cadencia: 0.1
  Nombre: AMETRALLADORA
  AttackRange: 1000000
  Idx: 2
  Cadencia: 275856
  Precision: 0.5
CanionDeCadena:
  Nombre: CANION_DE_CADENA
  AttackRange: 1000000
  Idx: 3
  Cadencia: 68964
  Precision: 0.5
Cuchillo:
  Nombre: CUCHILLO
  AttackRange: 1
  Idx: 0
  Cadencia: -1
  Precision: 0
LanzaCohetes:
  Nombre: LANZA_COHETES
  AttackRange: 1000000
  Idx: 4
  Cadencia: -1
  Precision: 0
Pistola:
  Nombre: PISTOLA
  AttackRange: 1000000
  Idx: 1
  Cadencia: -1
  Precision: 0.2
Blood:
  Points: 1
Food:
  Points: 10
Medkit:
  Points: 20
Treasure:
  Points: 50
Moves:
  Step: 0.1
  RotationLeft: 0.1
  RotationRight: -0.1
Game:
  GameTime: 30000
  LobbyTime: 20
  FPS: 29
Server:
  Hostname: localhost
  Port: 9006
Maps:
  Location: ../maps/
MapsSequence:
  - map1.yml
  - map2.yml