#ifndef __ITEM_TYPE_H__
#define __ITEM_TYPE_H__

enum ItemType { 
	TYPE_BULLETS = 1,
	TYPE_FOOD = 2,
	TYPE_ARMA_CANION = 3,
	TYPE_ARMA_AMETRALLADORA = 4,
	TYPE_ARMA_LANZACOHETES = 5,
	TYPE_BARREL = 6,
	TYPE_BLOOD = 7,
	TYPE_CORPSE = 8,
	TYPE_KEY = 9,
	TYPE_MEDKIT = 10,
	TYPE_TABLE = 11,
	TYPE_TREASURE = 12,
	TYPE_WATER = 13
};

#endif
