server:
  host: localhost
  port: 9006
FPS_cap: 29
graphics:
  FOV: 1.0472
  wall_height: 1.5
window:
  title: FIUBAstein 3D
  width: 640
  height: 480
menu_ui:
  matches_box:
    x_pos: 100
    y_pos: 100
    width: 440
    height: 300
    gilding: 3
  maps_box:
    x_pos: 100
    y_pos: 100
    width: 440
    height: 300
    gilding: 3
  directory: ../assets/menu_ui/
  font: wolfenstein.ttf
  background: background.png
game_ui:
  directory: ../assets/game_ui/
  key_icon:
    texture: key_icon.png
    x_pos: 10
    y_pos: 300
    width: 80
    height: 60
  font: menufont.ttf
  bar:
    x_pos: 0
    y_pos: 400
    width: 640
    height: 80
    texture: ui_bar.png
walls:
  directory: ../assets/textures/walls/
  files:
    - wood.png
    - bluestone.png
    - colorstone.png
    - eagle.png
    - greystone.png
props:
  directory: ../assets/textures/props/
  files: 
    - barrel.png
    - greenlight.png
    - pillar.png
consumables:
  directory: ../assets/textures/consumables/
animations:
  enemies:
    directory: ../assets/sprites/enemies/
    sprites:
      - file: ss.png
        frames: 5
        frame_width: 64
        frame_height: 64
      - file: ss.png
        frames: 5
        frame_width: 64
        frame_height: 64
      - file: ss.png
        frames: 5
        frame_width: 64
        frame_height: 64
      - file: ss.png
        frames: 5
        frame_width: 64
        frame_height: 64
      - file: ss.png
        frames: 5
        frame_width: 64
        frame_height: 64