server:
  host: localhost
  port: 9006
FPS_cap: 60
graphics:
  FOV: 1.0472
  wall_height: 1.5
music:
  directory: ../assets/music/
  menu: searching_for_the_enemy.wav
  game: funk_you.wav
window:
  title: FIUBAstein 3D
  width: 640
  height: 480
menu_ui:
  matches_box:
    x_pos: 100
    y_pos: 100
    width: 440
    height: 300
    gilding: 3
  maps_box:
    x_pos: 100
    y_pos: 100
    width: 440
    height: 300
    gilding: 3
  lobby_box:
    x_pos: 100
    y_pos: 100
    width: 440
    height: 200
    gilding: 3
    header_text:
      x_pos: 320
      y_pos: 130
      text: Waiting for players...
    time_text:
      x_pos: 250
      y_pos: 170
      text: 'Time remaining: '
    players_text:
      x_pos: 170
      y_pos: 210
      text: 'Players: '
    back_text:
      x_pos: 320
      y_pos: 330
      text: CANCEL
  directory: ../assets/menu_ui/
  font: wolfenstein.ttf
  background: background.png
game_ui:
  directory: ../assets/game_ui/
  key_icon:
    texture: key_icon.png
    x_pos: 10
    y_pos: 300
    width: 80
    height: 60
  font: menufont.ttf
  bar:
    x_pos: 0
    y_pos: 400
    width: 640
    height: 80
    texture: ui_bar.png
walls:
  directory: ../assets/textures/walls/
  files:
    - wood.png
    - bluestone.png
    - colorstone.png
    - eagle.png
    - greystone.png
props:
  directory: ../assets/textures/props/
  files: 
    - barrel.png
    - greenlight.png
    - pillar.png
items:
  directory: ../assets/textures/items/
  files:
    - bullets.png
    - food.png
    - cannon.png
    - machine_gun.png
    - rocket_launcher.png
    - barrel.png
    - blood.png
    - corpse.png
    - key.png
    - medkit.png
    - table.png
    - treasure.png
    - water.png
weapons:
  - directory: ../assets/player_weapons/knife/
    sfx: stabbing.wav
    x_pos: 120
    y_pos: 310
    width: 420
    height: 120
    steps: 12
    idle:
      - knife_idle.png
    shooting:
      - knife_stabbing_1.png
      - knife_stabbing_2.png
  - directory: ../assets/player_weapons/pistol/
    sfx: shooting.wav
    x_pos: 120
    y_pos: 310
    width: 420
    height: 120
    steps: 12
    idle:
      - pistol_idle.png
    shooting:
      - pistol_shooting_1.png
      - pistol_shooting_2.png
animations:
  # weapons:
  #   - directory: ../assets/sprites/player_weapons/knife/
  #     x_pos: 120
  #     y_pos: 310
  #     width: 420
  #     height: 120
  #     steps: 12
  #     idle:
  #       - knife_idle.png
  #     shooting:
  #       - knife_stabbing_1.png
  #       - knife_stabbing_2.png
  #   - directory: ../assets/sprites/player_weapons/pistol/
  #     x_pos: 120
  #     y_pos: 310
  #     width: 420
  #     height: 120
  #     steps: 12
  #     idle:
  #       - pistol_idle.png
  #     shooting:
  #       - pistol_shooting_1.png
  #       - pistol_shooting_2.png
  enemies:
    directory: ../assets/sprites/enemies/
    sprite_sets:
      - directory: ss/
        sprites:
          idle:
            - idle_front.png
          move_forward:
            - moving_front_1.png
            - moving_front_2.png
            - moving_front_3.png
            - moving_front_4.png
          shooting:
            - shooting_1.png
            - shooting_2.png
            - shooting_3.png
          dying:
            - dying_1.png
            - dying_2.png
            - dying_3.png
            - dying_4.png
            - dying_5.png